### ISSUE TITLE
My Texture Pack Crashes the Game

### ISSUE THREAD

**Issue by cdymrtn** [Zowja/New-Frontier-Craft#6]
I've been trying to continue making my old texture pack for NFC but if I have my texture pack in the texture pack folder and try to go to the Mods and Texture packs menu in-game, the game will crash. I already downloaded Space's texture pack and it works just fine even though his texture pack said to use Optifine, so, I tried to setup my texture pack just like Space's but it still crashes for some reason.

Here is the error report that Minecraft gives me.

> --- BEGIN ERROR REPORT a1dce528 --------
> Generated 6/20/18 4:28 PM
> 
> Minecraft: Minecraft Beta 1.7.3
> OS: Windows 10 (amd64) version 10.0
> Java: 1.8.0_171, Oracle Corporation
> VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> LWJGL: 2.9.0
> OpenGL: AMD Radeon (TM) R9 Fury Series version 4.5.13507 Compatibility Profile Context 23.20.15027.1004, ATI Technologies Inc.
> 
> java.nio.BufferOverflowException
> 	at java.nio.DirectByteBuffer.put(Unknown Source)
> 	at java.nio.ByteBuffer.put(Unknown Source)
> 	at ji.a(SourceFile:233)
> 	at ji.a(SourceFile:171)
> 	at vp.c(SourceFile:73)
> 	at de.a(SourceFile:148)
> 	at lg.a(GuiSlot.java:223)
> 	at ft.a(GuiTexturePacks.java:61)
> 	at px.b(SourceFile:553)
> 	at net.minecraft.client.Minecraft.run(Minecraft.java:469)
> 	at java.lang.Thread.run(Unknown Source)
> --- END ERROR REPORT 33e8c119 ----------
>

**Comment by cdymrtn** [comment]
I believe the issue was my own doing, as I was thinking before, I probably had a texture I sized wrong or something and that is probably what caused the game to crash. I just created a standard texture pack with the NFC texture files and it works without crashing, even edited the terrain.png and it still works without crashing the game. I just check my textures for size to see if that truly was the issue and I had the pack.png set to a really high resolution.
